# Generated by Django 4.1.5 on 2023-01-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_snipped_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='snipped',
            new_name='snippet',
        ),
    ]
